project_name: spam local
project_id: 7bce834a-bd56-4fa6-89d6-dcd2acb0b4cd
project_description: testing spam on local
project_task_type: text_classification
training_run_id: 7b1be4c4-084d-46d7-948d-12b04b26b049
training_s3_path: media/projects/7bce834a-bd56-4fa6-89d6-dcd2acb0b4cd/7b1be4c4-084d-46d7-948d-12b04b26b049
config_s3_path: media/projects/7bce834a-bd56-4fa6-89d6-dcd2acb0b4cd/7b1be4c4-084d-46d7-948d-12b04b26b049/config.yaml
config_file_path: projects_yaml/config.yaml
prompt_id: c2e62aa3-cb7f-43e1-ba57-5817909ef04a
prompt_name: short prompt
system_prompt: You are a helpful assistant that classifies text messages as spam or
  not spam. For each message, respond with 'spam' or 'not spam'
think_flag: true
seed_text: ''
train_dataset_id: 996c0774-5676-41d9-a94b-b5b78d694828
train_s3_path: media/projects/7bce834a-bd56-4fa6-89d6-dcd2acb0b4cd/train/spam_train_test.csv
train_file_name: spam_train_test.csv
train_file_path: data/spam_train_test.csv
eval_dataset_id: a11fe5b8-639a-4486-b215-f3e1b4e29216
eval_s3_path: media/projects/7bce834a-bd56-4fa6-89d6-dcd2acb0b4cd/eval/spam_cv_test.csv
eval_file_name: spam_cv_test.csv
eval_file_path: data/spam_cv_test.csv
cv_file_path: data/spam_cv_test.csv
reward: classify_text
ref_model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
max_new_tokens: 2
trajectory_name: run_1
trajectory_count: 2
start_iteration: 1
topk: 1
save_every_epoch: 1
accumulation_steps: 1
no_epochs: 1
no_iterations: 1
loss: gspo
model_epoch: 1
topk_eval: 1
