project_name: classify_spam_local

system_prompt:
    You are a helpful assistant that classifies text messages as spam or not spam.
    For each message, respond with 'spam' or 'not spam'.
think_flag: true
seed_text: "Let me analyze this message..."

train_file_path: data/spam_train_test.csv
cv_file_path: data/spam_cv_test.csv
trajectory_name: run_1
training_name: run_1
trajectory_count: 2
ref_model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
max_new_tokens: 2
reward : classify_text
model_epoch : 1
start_iteration : 1
topk : 1
topk_eval : 1
save_every_epoch : 1
accumulation_steps : 1
no_epochs : 1
no_iterations : 1
loss : gspo