trajectory_name: run_1
training_name: run_1
trajectory_count: 10
ref_model_name: Qwen/Qwen2-VL-7B-Instruct
model_name: Qwen/Qwen2-VL-7B-Instruct
max_new_tokens: 250
reward : image_extraction
model_epoch : 1
start_iteration : 2
topk : 1
topk_trajectory: 50
topk_eval : 1
save_every_epoch : 1
accumulation_steps : 1
no_epochs : 1
no_iterations : 2
loss : grpo