trajectory_name: run_1
training_name: run_1
trajectory_count: 10
ref_model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
max_new_tokens: 250
reward : classify_text
model_epoch : 1
start_iteration : 1
topk : 1
topk_eval : 1
save_every_epoch : 1
accumulation_steps : 1
no_epochs : 3
no_iterations : 3
loss : grpo